### ISSUE TITLE
No module named QtWebKit 

### ISSUE THREAD

**Issue by robd518** [jeanphix/Ghost.py#262]
I'm on CentOS 7.  I don't understand this.

```
sudo pip install Ghost.py

Collecting Ghost.py
/usr/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading Ghost.py-0.2.3.tar.gz (220kB)
    100% |████████████████████████████████| 221kB 2.2MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-YImhjW/Ghost.py/setup.py", line 9, in <module>
        from ghost import __version__
      File "ghost/__init__.py", line 2, in <module>
        from .ghost import (
      File "ghost/ghost.py", line 17, in <module>
        from .bindings import (
      File "ghost/bindings.py", line 74, in <module>
        QtWebKit = _import('QtWebKit')
      File "ghost/bindings.py", line 41, in _import
        module = __import__(name)
    ImportError: No module named QtWebKit

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-YImhjW/Ghost.py
```

This simply isn't true, though.

```
user@host:~$python
Python 2.7.5 (default, Jun 24 2015, 00:41:19) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt4 import QtWebKit
```

Prior to all this, I did the following:

```
sudo yum install epel-release
sudo yum update
sudo yum install cmake qconf qt-devel qt4-devel python-devel PyQt4 PyQt4-devel PyQt4-web*
sudo ln -s /usr/bin/qmake-qt4 /usr/bin/qmake
```

I'm not sure what I'm doing wrong.

**Comment by openrijal** [comment]
Hi @muddafugga 

Did you get any progress on this? I'm getting the same thing on CentOS 7 as well.

**Comment by robd518** [comment]
@crackjack I wound up giving up and moving on to other projects.

**Comment by openrijal** [comment]
@muddafugga what other projects have you considered? would be nice to know.

**Comment by phoenixz** [comment]
@muddafugga Same here, would be nice to know what alternatives are out there

**Comment by robd518** [comment]
Sorry @crackjack @phoenixz I meant that I moved on to doing other things, not that I moved on to another project like Ghost.py.  I am not sure there are other alternatives out there, but for me, I gave up.   :(

**Comment by EvaSDK** [comment]
So I just setup a VM on CentOS 7.4 to check this issue and could not reproduce. Here is what I did after installing and updating the default install:
```
# yum install epel-release
# yum install PyQt4 PyQt4-webkit
# yum install python-virtualenv
# virtualenv venv
# . venv/bin/activate
# pip install Ghost.py
```

Are you still able to reproduce the issue ?
