### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'url'

### ISSUE THREAD

**Issue by piterjoin** [jeanphix/Ghost.py#266]
```python
from ghost import Ghost
import re
ghost = Ghost()
with ghost.start(wait_timeout=20) as session:
    url_re = "<span class=\"g\">(.*?)<"
    page, extra_resources = session.open("http://www.baidu.com/s?wd=google&pn=1")
    print "step 1"
    links = re.findall(url_re,page.content)
    for link in links:
        print "get link ",link
    page_num=1
    print "step 2"
    while page_num < 10:
        if 'class="n"' in str(page.content):
            print "step 3"
            session.click('.n')
            page, resources = session.wait_for_page_loaded()
            session.wait_for_selector('.n')
            print "step 4"
            print page.url
            links = re.findall(url_re,page.content)
            for link in links:
                print "get link ",link
            page_num = page_num+1
        else:
            break
```

Result:
```
2015-09-23T03:30:50.344Z [WARNING ] QT: libpng warning: iCCP: known incorrect sRGB profile
2015-09-23T03:30:52.138Z [WARNING ] Ghost<ca9937c7-8d7f-4b5d-bdab-fe72d2fb19a6>: undefined(0): ReferenceError: Can't find variable: cb_15517027_0
step 1
get link  translate.
get link  www.g.cn/&nbsp;
get link  dl.pconline.com.cn/dow...&nbsp;
get link  www.
get link  www.earthol.com/&nbsp;
get link  scholar.
step 2
step 3
step 4
Traceback (most recent call last):
  File "D:\pyscan\scanner\getdomain\ghosts.py", line 23, in <module>
    print page.url
AttributeError: 'NoneType' object has no attribute 'url'
# 

session.wait_for_selector('.n') 能够执行
但是page 为“NoneType”，内容都不见了？
```

**Comment by stdex** [comment]
```python
from ghost import Ghost
import re

ghost = Ghost()
with ghost.start(wait_timeout=100) as session:
    url_re = "(.*?)<"
    page, extra_resources = session.open("http://www.baidu.com/s?wd=google&pn=1", timeout=100)
    print ("step 1")
    links = re.findall(url_re,page.content)
    for link in links:
        print ("get link ",link)
        page_num=1
        print ("step 2")
        while page_num < 10:
            if 'class="n"' in str(page.content):
                print ("step 3")
                session.click('.n')
                page, resources = session.wait_for_page_loaded()
                session.wait_for_selector('.n')
                print ("step 4")
                print (page.url)
                links = re.findall(url_re,page.content)
                for link in links:
                    print ("get link ",link)
                    page_num = page_num+1
            else:
                break
```

For me it return:

```
Traceback (most recent call last):
  File "baidu.py", line 7, in <module>
    page, extra_resources = session.open("http://www.baidu.com/s?wd=google&pn=1", timeout=100)
  File "/usr/local/lib/python3.4/dist-packages/ghost/ghost.py", line 901, in open
    return self.wait_for_page_loaded(timeout=timeout)
  File "/usr/local/lib/python3.4/dist-packages/ghost/ghost.py", line 1196, in wait_for_page_loaded
    'Unable to load requested page', timeout)
  File "/usr/local/lib/python3.4/dist-packages/ghost/ghost.py", line 1174, in wait_for
    raise TimeoutError(timeout_message)
ghost.ghost.TimeoutError: Unable to load requested page
```
