### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by BMeridian** [jeanphix/Ghost.py#269]
For OSX

> pyside_postinstall.py -install

Does not run.

Then the next step does not run. 

> pip install ghost.py 

Collecting ghost.py
  Using cached Ghost.py-0.2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/81/8g2lrjg97j3_0rwpr32zqsf40000gn/T/pip-build-zCSJSA/ghost.py/setup.py", line 9, in <module>
        from ghost import **version**
      File "ghost/**init**.py", line 2, in <module>
        from .ghost import (
      File "ghost/ghost.py", line 17, in <module>
        from .bindings import (
      File "ghost/bindings.py", line 47, in <module>
        QtCore = _import("QtCore")
      File "ghost/bindings.py", line 41, in _import
        module = __import__(name)
    ImportError: dlopen(/usr/local/lib/python2.7/site-packages/PySide/QtCore.so, 2): Library not loaded: libpyside-python2.7.1.2.dylib
      Referenced from: /usr/local/lib/python2.7/site-packages/PySide/QtCore.so
      Reason: image not found

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/81/8g2lrjg97j3_0rwpr32zqsf40000gn/T/pip-build-zCSJSA/ghost.py

**Comment by ghost** [comment]
Same problem with you. Please tell me if you find the solutions. Thanks a lot.

**Comment by stdex** [comment]
1) `Library not loaded: libpyside-python2.7.1.2.dylib`
2) Use pip for install pyside
