### ISSUE TITLE
AttributeError: 'module' object has no attribute 'QSslConfiguration'

### ISSUE THREAD

**Issue by nottug** [jeanphix/Ghost.py#301]
When attempting to import ghost.py, I run into this issue:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/ghost/__init__.py", line 2, in <module>
    from .ghost import (
  File "/usr/local/lib/python2.7/site-packages/ghost/ghost.py", line 17, in <module>
    from .bindings import (
  File "/usr/local/lib/python2.7/site-packages/ghost/bindings.py", line 71, in <module>
    QSslConfiguration = QtNetwork.QSslConfiguration
AttributeError: 'module' object has no attribute 'QSslConfiguration'`

I am on OS X 10.11.5

**Comment by charlesg** [comment]
Was it something obvious, I just ran into the same thing trying to install within Anaconda Python:

```
  Using cached Ghost.py-0.2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-SGD8Wh/Ghost.Py/setup.py", line 9, in <module>
        from ghost import __version__
      File "ghost/__init__.py", line 2, in <module>
        from .ghost import (
      File "ghost/ghost.py", line 17, in <module>
        from .bindings import (
      File "ghost/bindings.py", line 71, in <module>
        QSslConfiguration = QtNetwork.QSslConfiguration
    AttributeError: 'module' object has no attribute 'QSslConfiguration'
```
