### ISSUE TITLE
Got an unexpected keyword argument 'wait_timeout'

### ISSUE THREAD

**Issue by isurusam** [jeanphix/Ghost.py#306]
When I try to define the wait_timeout in Ghost constructor it gives me the below error. 

> Traceback (most recent call last):
>   File "C:\Anaconda3\lib\site-packages\ghost\ghost.py", line 325, in **del**
>     self.exit()
>   File "C:\Anaconda3\lib\site-packages\ghost\ghost.py", line 315, in exit
>     self._app.quit()
> AttributeError: 'NoneType' object has no attribute 'quit'
> Traceback (most recent call last):
>   File "testGhost.py", line 2, in <module>
>     ghost = Ghost(wait_timeout=30)
> TypeError: __init__() got an unexpected keyword argument 'wait_timeout'

My program is:

`from ghost import Ghost
ghost = Ghost(wait_timeout=30)

with ghost.start() as session:
    page, extra_resources = session.open("https://github.com")
    print ("Page Loaded")`

**Comment by isurusam** [comment]
I tried a different approach and it worked. Below is the code. 

```
from ghost import Ghost, Session

ghost = Ghost()
session = Session(ghost)
session.wait_timeout=25

#Open Webpage
ghost.open("http://girhub.com")
print ("page Loaded")
```
