### ISSUE TITLE
ImportError: No module named 'PySide2'

### ISSUE THREAD

**Issue by ghost** [jeanphix/Ghost.py#331]
Trying to import Ghost.py (from ghost import Ghost), installed PyQt on Python 3.4

Keep on getting a module error

Traceback (most recent call last):
  File "F:\Freelance Work\fineproxy.org_ip.py", line 10, in <module>
    from ghost import Ghost
  File "C:\Python34\lib\site-packages\ghost\__init__.py", line 1, in <module>
    from .ghost import (
  File "C:\Python34\lib\site-packages\ghost\ghost.py", line 13, in <module>
    from PySide2.QtWebKitWidgets import (
ImportError: No module named 'PySide2'
>>> 

Can anyone help?

**Comment by jeanphix** [comment]
Ghost do not supports PyQt anymore.
