### ISSUE TITLE
__call__() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by dabula-s** [jeanphix/Ghost.py#333]
i got some exception with some sites: session.open('http://opu.ua')
but it works, for example, for session.open('http://ac.opu.ua')
Traceback:
File "/usr/local/lib/python3.5/dist-packages/ghost/ghost.py", line 856, in open
return self.wait_for_page_loaded(timeout=timeout)
File "/usr/local/lib/python3.5/dist-packages/ghost/ghost.py", line 1157, in wait_for_page_loaded
'Unable to load requested page', timeout)
File "/usr/local/lib/python3.5/dist-packages/ghost/ghost.py", line 1136, in wait_for
self.sleep()
File "/usr/local/lib/python3.5/dist-packages/ghost/ghost.py", line 1122, in sleep
self.ghost._app.processEvents()
TypeError: __call__() takes 3 positional arguments but 4 were given

**Comment by laurentL** [comment]
Same here
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/ghost/ghost.py", line 1255, in _request_ended
    content = reply.data
AttributeError: 'PySide2.QtNetwork.QNetworkReply' object has no attribute 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/ghost/ghost.py", line 1257, in _request_ended
    content = reply.readAll()
TypeError: __call__() takes 3 positional arguments but 4 were given
