### ISSUE TITLE
will the new version come out?

### ISSUE THREAD

**Issue by unicornlox** [jeanphix/Ghost.py#336]
There are major changes in QT5.9. That's why I make mistakes. will the new version come out?
example error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ghost/__init__.py", line 1, in <module>
    from .ghost import (
  File "/usr/local/lib/python3.6/dist-packages/ghost/ghost.py", line 13, in <module>
    from PySide2.QtWebKitWidgets import (
ModuleNotFoundError: No module named 'PySide2.QtWebKitWidgets'
```
I think the problem can be solved by using the from `PySide2.QtWebEngineWidgets import `command instead of `from PySide2.QtWebKitWidgets`.
Known qt5 now uses a chromium-based web engine

**Comment by iosifnicolae2** [comment]
Still doesn't work..

**Comment by dattatembare** [comment]
@opoudjis I didn't understand why its closed without any reason

**Comment by opoudjis** [comment]
Our ticket? We decided to stick with puppeteer.
