### ISSUE TITLE
Not working on window

### ISSUE THREAD

**Issue by ghost** [jeanphix/Ghost.py#337]
```
Traceback (most recent call last):
  File "D:/source/tools/Test.py", line 2, in <module>
    ghost = Ghost()
  File "C:\python32\python-2.7.10\lib\site-packages\ghost.py-0.2.3-py2.7.egg\ghost\ghost.py", line 455, in __init__
    os.environ['DISPLAY'])
  File "C:\python32\python-2.7.10\lib\os.py", line 425, in __getitem__
    return self.data[key.upper()]
KeyError: 'DISPLAY'

```

**Comment by EvaSDK** [comment]
Code you please give a shot at ghost-py-0-2 branch ?
