### ISSUE TITLE
Exception: Unable to load requested page

### ISSUE THREAD

**Issue by kravietz** [jeanphix/Ghost.py#87]
Latest GitHub clone is unable to load more complex pages and it crashes on timeouts. Small pages load, but if the page has any external content (like images) I get this exception:

```
>>> g.open('http://example.com/glb_home/en/home.jsp')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/Ghost.py-0.1b2-py2.7.egg/ghost/ghost.py", line 560, in open
    return self.wait_for_page_loaded()
  File "/usr/local/lib/python2.7/dist-packages/Ghost.py-0.1b2-py2.7.egg/ghost/ghost.py", line 774, in wait_for_page_loaded
    'Unable to load requested page')
  File "/usr/local/lib/python2.7/dist-packages/Ghost.py-0.1b2-py2.7.egg/ghost/ghost.py", line 755, in wait_for
    raise Exception(timeout_message)
Exception: Unable to load requested page
```

Looking at sniffer output I see that Ghost actually requests all these external files (and receives them), but then it somehow crashes on a timeout. I tested it on many pages and it was consistent behavior.

**Comment by socrateslee** [comment]
the same as mintigo-efi on ubuntu 14.04, got the timeout exception with pyqt4 but working after installing pyside(apt-get install python-pyside).

**Comment by muddafugga** [comment]
Wow am I late to this party!  I also had luck in setting the timeout higher than the default of 8.  Some things must have also changed in the code since OP, because ghost = Ghost(wait_timeout=999) doesn't work.  I am able to get it to work by doing the following:
ghost = Ghost()
session = ghost.start()
session.wait_timeout = 999
session.open(your url)

**Comment by dbr7** [comment]
@muddafugga Thanks! it works for me

**Comment by frank0718** [comment]
session.wait_timeout = 999 worked

**Comment by peterchaula** [comment]
For beginners. **Do not** run ghost in terminal emulator. Run in file

**Comment by mickelfeng** [comment]
@frank0718  yes ,it works， but the process is blocked ,still waiting.  I think selenium+ phantomjs is more stable than Ghost.py
